; Auto-generated. Do not edit!


(cl:in-package planning-msg)


;//! \htmlinclude LTP_Plan.msg.html

(cl:defclass <LTP_Plan> (roslisp-msg-protocol:ros-message)
  ((pos_x_list
    :reader pos_x_list
    :initarg :pos_x_list
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (pos_y_list
    :reader pos_y_list
    :initarg :pos_y_list
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (vel_x_list
    :reader vel_x_list
    :initarg :vel_x_list
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (vel_y_list
    :reader vel_y_list
    :initarg :vel_y_list
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass LTP_Plan (<LTP_Plan>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LTP_Plan>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LTP_Plan)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name planning-msg:<LTP_Plan> is deprecated: use planning-msg:LTP_Plan instead.")))

(cl:ensure-generic-function 'pos_x_list-val :lambda-list '(m))
(cl:defmethod pos_x_list-val ((m <LTP_Plan>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planning-msg:pos_x_list-val is deprecated.  Use planning-msg:pos_x_list instead.")
  (pos_x_list m))

(cl:ensure-generic-function 'pos_y_list-val :lambda-list '(m))
(cl:defmethod pos_y_list-val ((m <LTP_Plan>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planning-msg:pos_y_list-val is deprecated.  Use planning-msg:pos_y_list instead.")
  (pos_y_list m))

(cl:ensure-generic-function 'vel_x_list-val :lambda-list '(m))
(cl:defmethod vel_x_list-val ((m <LTP_Plan>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planning-msg:vel_x_list-val is deprecated.  Use planning-msg:vel_x_list instead.")
  (vel_x_list m))

(cl:ensure-generic-function 'vel_y_list-val :lambda-list '(m))
(cl:defmethod vel_y_list-val ((m <LTP_Plan>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planning-msg:vel_y_list-val is deprecated.  Use planning-msg:vel_y_list instead.")
  (vel_y_list m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LTP_Plan>) ostream)
  "Serializes a message object of type '<LTP_Plan>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'pos_x_list))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pos_x_list))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'pos_y_list))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pos_y_list))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'vel_x_list))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'vel_x_list))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'vel_y_list))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'vel_y_list))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LTP_Plan>) istream)
  "Deserializes a message object of type '<LTP_Plan>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'pos_x_list) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'pos_x_list)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'pos_y_list) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'pos_y_list)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'vel_x_list) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'vel_x_list)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'vel_y_list) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'vel_y_list)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LTP_Plan>)))
  "Returns string type for a message object of type '<LTP_Plan>"
  "planning/LTP_Plan")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LTP_Plan)))
  "Returns string type for a message object of type 'LTP_Plan"
  "planning/LTP_Plan")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LTP_Plan>)))
  "Returns md5sum for a message object of type '<LTP_Plan>"
  "65ed2aaf51836053f56cfd7ad4d3b5d0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LTP_Plan)))
  "Returns md5sum for a message object of type 'LTP_Plan"
  "65ed2aaf51836053f56cfd7ad4d3b5d0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LTP_Plan>)))
  "Returns full string definition for message of type '<LTP_Plan>"
  (cl:format cl:nil "float32[] pos_x_list~%float32[] pos_y_list~%float32[] vel_x_list~%float32[] vel_y_list~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LTP_Plan)))
  "Returns full string definition for message of type 'LTP_Plan"
  (cl:format cl:nil "float32[] pos_x_list~%float32[] pos_y_list~%float32[] vel_x_list~%float32[] vel_y_list~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LTP_Plan>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'pos_x_list) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'pos_y_list) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'vel_x_list) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'vel_y_list) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LTP_Plan>))
  "Converts a ROS message object to a list"
  (cl:list 'LTP_Plan
    (cl:cons ':pos_x_list (pos_x_list msg))
    (cl:cons ':pos_y_list (pos_y_list msg))
    (cl:cons ':vel_x_list (vel_x_list msg))
    (cl:cons ':vel_y_list (vel_y_list msg))
))
